/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClustersIndexRouteImport } from './routes/clusters/index'
import { Route as ClustersClusterIdRouteRouteImport } from './routes/clusters/$clusterId/route'
import { Route as ClustersClusterIdLogsRouteImport } from './routes/clusters/$clusterId/logs'
import { Route as ClustersClusterIdInstancesRouteImport } from './routes/clusters/$clusterId/instances'
import { Route as ClustersClusterIdGraphRouteImport } from './routes/clusters/$clusterId/graph'
import { Route as ClustersClusterIdEventsRouteImport } from './routes/clusters/$clusterId/events'
import { Route as ClustersClusterIdDashboardRouteImport } from './routes/clusters/$clusterId/dashboard'
import { Route as ClustersClusterIdConsoleRouteImport } from './routes/clusters/$clusterId/console'
import { Route as ClustersClusterIdSettingsRouteRouteImport } from './routes/clusters/$clusterId/settings/route'
import { Route as ClustersClusterIdServicesIndexRouteImport } from './routes/clusters/$clusterId/services/index'
import { Route as ClustersClusterIdDeploymentsIndexRouteImport } from './routes/clusters/$clusterId/deployments/index'
import { Route as ClustersClusterIdSettingsUsersRouteImport } from './routes/clusters/$clusterId/settings/users'
import { Route as ClustersClusterIdSettingsProfileRouteImport } from './routes/clusters/$clusterId/settings/profile'
import { Route as ClustersClusterIdSettingsIntegrationsRouteImport } from './routes/clusters/$clusterId/settings/integrations'
import { Route as ClustersClusterIdSettingsConfigRouteImport } from './routes/clusters/$clusterId/settings/config'
import { Route as ClustersClusterIdServicesIdRouteImport } from './routes/clusters/$clusterId/services/$id'
import { Route as ClustersClusterIdDeploymentsIdRouteImport } from './routes/clusters/$clusterId/deployments/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClustersIndexRoute = ClustersIndexRouteImport.update({
  id: '/clusters/',
  path: '/clusters/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClustersClusterIdRouteRoute = ClustersClusterIdRouteRouteImport.update({
  id: '/clusters/$clusterId',
  path: '/clusters/$clusterId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClustersClusterIdLogsRoute = ClustersClusterIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ClustersClusterIdRouteRoute,
} as any)
const ClustersClusterIdInstancesRoute =
  ClustersClusterIdInstancesRouteImport.update({
    id: '/instances',
    path: '/instances',
    getParentRoute: () => ClustersClusterIdRouteRoute,
  } as any)
const ClustersClusterIdGraphRoute = ClustersClusterIdGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => ClustersClusterIdRouteRoute,
} as any)
const ClustersClusterIdEventsRoute = ClustersClusterIdEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ClustersClusterIdRouteRoute,
} as any)
const ClustersClusterIdDashboardRoute =
  ClustersClusterIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ClustersClusterIdRouteRoute,
  } as any)
const ClustersClusterIdConsoleRoute =
  ClustersClusterIdConsoleRouteImport.update({
    id: '/console',
    path: '/console',
    getParentRoute: () => ClustersClusterIdRouteRoute,
  } as any)
const ClustersClusterIdSettingsRouteRoute =
  ClustersClusterIdSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ClustersClusterIdRouteRoute,
  } as any)
const ClustersClusterIdServicesIndexRoute =
  ClustersClusterIdServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => ClustersClusterIdRouteRoute,
  } as any)
const ClustersClusterIdDeploymentsIndexRoute =
  ClustersClusterIdDeploymentsIndexRouteImport.update({
    id: '/deployments/',
    path: '/deployments/',
    getParentRoute: () => ClustersClusterIdRouteRoute,
  } as any)
const ClustersClusterIdSettingsUsersRoute =
  ClustersClusterIdSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => ClustersClusterIdSettingsRouteRoute,
  } as any)
const ClustersClusterIdSettingsProfileRoute =
  ClustersClusterIdSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => ClustersClusterIdSettingsRouteRoute,
  } as any)
const ClustersClusterIdSettingsIntegrationsRoute =
  ClustersClusterIdSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => ClustersClusterIdSettingsRouteRoute,
  } as any)
const ClustersClusterIdSettingsConfigRoute =
  ClustersClusterIdSettingsConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => ClustersClusterIdSettingsRouteRoute,
  } as any)
const ClustersClusterIdServicesIdRoute =
  ClustersClusterIdServicesIdRouteImport.update({
    id: '/services/$id',
    path: '/services/$id',
    getParentRoute: () => ClustersClusterIdRouteRoute,
  } as any)
const ClustersClusterIdDeploymentsIdRoute =
  ClustersClusterIdDeploymentsIdRouteImport.update({
    id: '/deployments/$id',
    path: '/deployments/$id',
    getParentRoute: () => ClustersClusterIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clusters/$clusterId': typeof ClustersClusterIdRouteRouteWithChildren
  '/clusters': typeof ClustersIndexRoute
  '/clusters/$clusterId/settings': typeof ClustersClusterIdSettingsRouteRouteWithChildren
  '/clusters/$clusterId/console': typeof ClustersClusterIdConsoleRoute
  '/clusters/$clusterId/dashboard': typeof ClustersClusterIdDashboardRoute
  '/clusters/$clusterId/events': typeof ClustersClusterIdEventsRoute
  '/clusters/$clusterId/graph': typeof ClustersClusterIdGraphRoute
  '/clusters/$clusterId/instances': typeof ClustersClusterIdInstancesRoute
  '/clusters/$clusterId/logs': typeof ClustersClusterIdLogsRoute
  '/clusters/$clusterId/deployments/$id': typeof ClustersClusterIdDeploymentsIdRoute
  '/clusters/$clusterId/services/$id': typeof ClustersClusterIdServicesIdRoute
  '/clusters/$clusterId/settings/config': typeof ClustersClusterIdSettingsConfigRoute
  '/clusters/$clusterId/settings/integrations': typeof ClustersClusterIdSettingsIntegrationsRoute
  '/clusters/$clusterId/settings/profile': typeof ClustersClusterIdSettingsProfileRoute
  '/clusters/$clusterId/settings/users': typeof ClustersClusterIdSettingsUsersRoute
  '/clusters/$clusterId/deployments': typeof ClustersClusterIdDeploymentsIndexRoute
  '/clusters/$clusterId/services': typeof ClustersClusterIdServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clusters/$clusterId': typeof ClustersClusterIdRouteRouteWithChildren
  '/clusters': typeof ClustersIndexRoute
  '/clusters/$clusterId/settings': typeof ClustersClusterIdSettingsRouteRouteWithChildren
  '/clusters/$clusterId/console': typeof ClustersClusterIdConsoleRoute
  '/clusters/$clusterId/dashboard': typeof ClustersClusterIdDashboardRoute
  '/clusters/$clusterId/events': typeof ClustersClusterIdEventsRoute
  '/clusters/$clusterId/graph': typeof ClustersClusterIdGraphRoute
  '/clusters/$clusterId/instances': typeof ClustersClusterIdInstancesRoute
  '/clusters/$clusterId/logs': typeof ClustersClusterIdLogsRoute
  '/clusters/$clusterId/deployments/$id': typeof ClustersClusterIdDeploymentsIdRoute
  '/clusters/$clusterId/services/$id': typeof ClustersClusterIdServicesIdRoute
  '/clusters/$clusterId/settings/config': typeof ClustersClusterIdSettingsConfigRoute
  '/clusters/$clusterId/settings/integrations': typeof ClustersClusterIdSettingsIntegrationsRoute
  '/clusters/$clusterId/settings/profile': typeof ClustersClusterIdSettingsProfileRoute
  '/clusters/$clusterId/settings/users': typeof ClustersClusterIdSettingsUsersRoute
  '/clusters/$clusterId/deployments': typeof ClustersClusterIdDeploymentsIndexRoute
  '/clusters/$clusterId/services': typeof ClustersClusterIdServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clusters/$clusterId': typeof ClustersClusterIdRouteRouteWithChildren
  '/clusters/': typeof ClustersIndexRoute
  '/clusters/$clusterId/settings': typeof ClustersClusterIdSettingsRouteRouteWithChildren
  '/clusters/$clusterId/console': typeof ClustersClusterIdConsoleRoute
  '/clusters/$clusterId/dashboard': typeof ClustersClusterIdDashboardRoute
  '/clusters/$clusterId/events': typeof ClustersClusterIdEventsRoute
  '/clusters/$clusterId/graph': typeof ClustersClusterIdGraphRoute
  '/clusters/$clusterId/instances': typeof ClustersClusterIdInstancesRoute
  '/clusters/$clusterId/logs': typeof ClustersClusterIdLogsRoute
  '/clusters/$clusterId/deployments/$id': typeof ClustersClusterIdDeploymentsIdRoute
  '/clusters/$clusterId/services/$id': typeof ClustersClusterIdServicesIdRoute
  '/clusters/$clusterId/settings/config': typeof ClustersClusterIdSettingsConfigRoute
  '/clusters/$clusterId/settings/integrations': typeof ClustersClusterIdSettingsIntegrationsRoute
  '/clusters/$clusterId/settings/profile': typeof ClustersClusterIdSettingsProfileRoute
  '/clusters/$clusterId/settings/users': typeof ClustersClusterIdSettingsUsersRoute
  '/clusters/$clusterId/deployments/': typeof ClustersClusterIdDeploymentsIndexRoute
  '/clusters/$clusterId/services/': typeof ClustersClusterIdServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clusters/$clusterId'
    | '/clusters'
    | '/clusters/$clusterId/settings'
    | '/clusters/$clusterId/console'
    | '/clusters/$clusterId/dashboard'
    | '/clusters/$clusterId/events'
    | '/clusters/$clusterId/graph'
    | '/clusters/$clusterId/instances'
    | '/clusters/$clusterId/logs'
    | '/clusters/$clusterId/deployments/$id'
    | '/clusters/$clusterId/services/$id'
    | '/clusters/$clusterId/settings/config'
    | '/clusters/$clusterId/settings/integrations'
    | '/clusters/$clusterId/settings/profile'
    | '/clusters/$clusterId/settings/users'
    | '/clusters/$clusterId/deployments'
    | '/clusters/$clusterId/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clusters/$clusterId'
    | '/clusters'
    | '/clusters/$clusterId/settings'
    | '/clusters/$clusterId/console'
    | '/clusters/$clusterId/dashboard'
    | '/clusters/$clusterId/events'
    | '/clusters/$clusterId/graph'
    | '/clusters/$clusterId/instances'
    | '/clusters/$clusterId/logs'
    | '/clusters/$clusterId/deployments/$id'
    | '/clusters/$clusterId/services/$id'
    | '/clusters/$clusterId/settings/config'
    | '/clusters/$clusterId/settings/integrations'
    | '/clusters/$clusterId/settings/profile'
    | '/clusters/$clusterId/settings/users'
    | '/clusters/$clusterId/deployments'
    | '/clusters/$clusterId/services'
  id:
    | '__root__'
    | '/'
    | '/clusters/$clusterId'
    | '/clusters/'
    | '/clusters/$clusterId/settings'
    | '/clusters/$clusterId/console'
    | '/clusters/$clusterId/dashboard'
    | '/clusters/$clusterId/events'
    | '/clusters/$clusterId/graph'
    | '/clusters/$clusterId/instances'
    | '/clusters/$clusterId/logs'
    | '/clusters/$clusterId/deployments/$id'
    | '/clusters/$clusterId/services/$id'
    | '/clusters/$clusterId/settings/config'
    | '/clusters/$clusterId/settings/integrations'
    | '/clusters/$clusterId/settings/profile'
    | '/clusters/$clusterId/settings/users'
    | '/clusters/$clusterId/deployments/'
    | '/clusters/$clusterId/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClustersClusterIdRouteRoute: typeof ClustersClusterIdRouteRouteWithChildren
  ClustersIndexRoute: typeof ClustersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clusters/': {
      id: '/clusters/'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof ClustersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clusters/$clusterId': {
      id: '/clusters/$clusterId'
      path: '/clusters/$clusterId'
      fullPath: '/clusters/$clusterId'
      preLoaderRoute: typeof ClustersClusterIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clusters/$clusterId/logs': {
      id: '/clusters/$clusterId/logs'
      path: '/logs'
      fullPath: '/clusters/$clusterId/logs'
      preLoaderRoute: typeof ClustersClusterIdLogsRouteImport
      parentRoute: typeof ClustersClusterIdRouteRoute
    }
    '/clusters/$clusterId/instances': {
      id: '/clusters/$clusterId/instances'
      path: '/instances'
      fullPath: '/clusters/$clusterId/instances'
      preLoaderRoute: typeof ClustersClusterIdInstancesRouteImport
      parentRoute: typeof ClustersClusterIdRouteRoute
    }
    '/clusters/$clusterId/graph': {
      id: '/clusters/$clusterId/graph'
      path: '/graph'
      fullPath: '/clusters/$clusterId/graph'
      preLoaderRoute: typeof ClustersClusterIdGraphRouteImport
      parentRoute: typeof ClustersClusterIdRouteRoute
    }
    '/clusters/$clusterId/events': {
      id: '/clusters/$clusterId/events'
      path: '/events'
      fullPath: '/clusters/$clusterId/events'
      preLoaderRoute: typeof ClustersClusterIdEventsRouteImport
      parentRoute: typeof ClustersClusterIdRouteRoute
    }
    '/clusters/$clusterId/dashboard': {
      id: '/clusters/$clusterId/dashboard'
      path: '/dashboard'
      fullPath: '/clusters/$clusterId/dashboard'
      preLoaderRoute: typeof ClustersClusterIdDashboardRouteImport
      parentRoute: typeof ClustersClusterIdRouteRoute
    }
    '/clusters/$clusterId/console': {
      id: '/clusters/$clusterId/console'
      path: '/console'
      fullPath: '/clusters/$clusterId/console'
      preLoaderRoute: typeof ClustersClusterIdConsoleRouteImport
      parentRoute: typeof ClustersClusterIdRouteRoute
    }
    '/clusters/$clusterId/settings': {
      id: '/clusters/$clusterId/settings'
      path: '/settings'
      fullPath: '/clusters/$clusterId/settings'
      preLoaderRoute: typeof ClustersClusterIdSettingsRouteRouteImport
      parentRoute: typeof ClustersClusterIdRouteRoute
    }
    '/clusters/$clusterId/services/': {
      id: '/clusters/$clusterId/services/'
      path: '/services'
      fullPath: '/clusters/$clusterId/services'
      preLoaderRoute: typeof ClustersClusterIdServicesIndexRouteImport
      parentRoute: typeof ClustersClusterIdRouteRoute
    }
    '/clusters/$clusterId/deployments/': {
      id: '/clusters/$clusterId/deployments/'
      path: '/deployments'
      fullPath: '/clusters/$clusterId/deployments'
      preLoaderRoute: typeof ClustersClusterIdDeploymentsIndexRouteImport
      parentRoute: typeof ClustersClusterIdRouteRoute
    }
    '/clusters/$clusterId/settings/users': {
      id: '/clusters/$clusterId/settings/users'
      path: '/users'
      fullPath: '/clusters/$clusterId/settings/users'
      preLoaderRoute: typeof ClustersClusterIdSettingsUsersRouteImport
      parentRoute: typeof ClustersClusterIdSettingsRouteRoute
    }
    '/clusters/$clusterId/settings/profile': {
      id: '/clusters/$clusterId/settings/profile'
      path: '/profile'
      fullPath: '/clusters/$clusterId/settings/profile'
      preLoaderRoute: typeof ClustersClusterIdSettingsProfileRouteImport
      parentRoute: typeof ClustersClusterIdSettingsRouteRoute
    }
    '/clusters/$clusterId/settings/integrations': {
      id: '/clusters/$clusterId/settings/integrations'
      path: '/integrations'
      fullPath: '/clusters/$clusterId/settings/integrations'
      preLoaderRoute: typeof ClustersClusterIdSettingsIntegrationsRouteImport
      parentRoute: typeof ClustersClusterIdSettingsRouteRoute
    }
    '/clusters/$clusterId/settings/config': {
      id: '/clusters/$clusterId/settings/config'
      path: '/config'
      fullPath: '/clusters/$clusterId/settings/config'
      preLoaderRoute: typeof ClustersClusterIdSettingsConfigRouteImport
      parentRoute: typeof ClustersClusterIdSettingsRouteRoute
    }
    '/clusters/$clusterId/services/$id': {
      id: '/clusters/$clusterId/services/$id'
      path: '/services/$id'
      fullPath: '/clusters/$clusterId/services/$id'
      preLoaderRoute: typeof ClustersClusterIdServicesIdRouteImport
      parentRoute: typeof ClustersClusterIdRouteRoute
    }
    '/clusters/$clusterId/deployments/$id': {
      id: '/clusters/$clusterId/deployments/$id'
      path: '/deployments/$id'
      fullPath: '/clusters/$clusterId/deployments/$id'
      preLoaderRoute: typeof ClustersClusterIdDeploymentsIdRouteImport
      parentRoute: typeof ClustersClusterIdRouteRoute
    }
  }
}

interface ClustersClusterIdSettingsRouteRouteChildren {
  ClustersClusterIdSettingsConfigRoute: typeof ClustersClusterIdSettingsConfigRoute
  ClustersClusterIdSettingsIntegrationsRoute: typeof ClustersClusterIdSettingsIntegrationsRoute
  ClustersClusterIdSettingsProfileRoute: typeof ClustersClusterIdSettingsProfileRoute
  ClustersClusterIdSettingsUsersRoute: typeof ClustersClusterIdSettingsUsersRoute
}

const ClustersClusterIdSettingsRouteRouteChildren: ClustersClusterIdSettingsRouteRouteChildren =
  {
    ClustersClusterIdSettingsConfigRoute: ClustersClusterIdSettingsConfigRoute,
    ClustersClusterIdSettingsIntegrationsRoute:
      ClustersClusterIdSettingsIntegrationsRoute,
    ClustersClusterIdSettingsProfileRoute:
      ClustersClusterIdSettingsProfileRoute,
    ClustersClusterIdSettingsUsersRoute: ClustersClusterIdSettingsUsersRoute,
  }

const ClustersClusterIdSettingsRouteRouteWithChildren =
  ClustersClusterIdSettingsRouteRoute._addFileChildren(
    ClustersClusterIdSettingsRouteRouteChildren,
  )

interface ClustersClusterIdRouteRouteChildren {
  ClustersClusterIdSettingsRouteRoute: typeof ClustersClusterIdSettingsRouteRouteWithChildren
  ClustersClusterIdConsoleRoute: typeof ClustersClusterIdConsoleRoute
  ClustersClusterIdDashboardRoute: typeof ClustersClusterIdDashboardRoute
  ClustersClusterIdEventsRoute: typeof ClustersClusterIdEventsRoute
  ClustersClusterIdGraphRoute: typeof ClustersClusterIdGraphRoute
  ClustersClusterIdInstancesRoute: typeof ClustersClusterIdInstancesRoute
  ClustersClusterIdLogsRoute: typeof ClustersClusterIdLogsRoute
  ClustersClusterIdDeploymentsIdRoute: typeof ClustersClusterIdDeploymentsIdRoute
  ClustersClusterIdServicesIdRoute: typeof ClustersClusterIdServicesIdRoute
  ClustersClusterIdDeploymentsIndexRoute: typeof ClustersClusterIdDeploymentsIndexRoute
  ClustersClusterIdServicesIndexRoute: typeof ClustersClusterIdServicesIndexRoute
}

const ClustersClusterIdRouteRouteChildren: ClustersClusterIdRouteRouteChildren =
  {
    ClustersClusterIdSettingsRouteRoute:
      ClustersClusterIdSettingsRouteRouteWithChildren,
    ClustersClusterIdConsoleRoute: ClustersClusterIdConsoleRoute,
    ClustersClusterIdDashboardRoute: ClustersClusterIdDashboardRoute,
    ClustersClusterIdEventsRoute: ClustersClusterIdEventsRoute,
    ClustersClusterIdGraphRoute: ClustersClusterIdGraphRoute,
    ClustersClusterIdInstancesRoute: ClustersClusterIdInstancesRoute,
    ClustersClusterIdLogsRoute: ClustersClusterIdLogsRoute,
    ClustersClusterIdDeploymentsIdRoute: ClustersClusterIdDeploymentsIdRoute,
    ClustersClusterIdServicesIdRoute: ClustersClusterIdServicesIdRoute,
    ClustersClusterIdDeploymentsIndexRoute:
      ClustersClusterIdDeploymentsIndexRoute,
    ClustersClusterIdServicesIndexRoute: ClustersClusterIdServicesIndexRoute,
  }

const ClustersClusterIdRouteRouteWithChildren =
  ClustersClusterIdRouteRoute._addFileChildren(
    ClustersClusterIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClustersClusterIdRouteRoute: ClustersClusterIdRouteRouteWithChildren,
  ClustersIndexRoute: ClustersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
