/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpecsRouteImport } from './routes/specs'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeploymentsIndexRouteImport } from './routes/deployments/index'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as SettingsSystemRouteImport } from './routes/settings.system'
import { Route as SettingsConfigRouteImport } from './routes/settings.config'
import { Route as DeploymentsIdRouteImport } from './routes/deployments/$id'

const SpecsRoute = SpecsRouteImport.update({
  id: '/specs',
  path: '/specs',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsIndexRoute = DeploymentsIndexRouteImport.update({
  id: '/deployments/',
  path: '/deployments/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSystemRoute = SettingsSystemRouteImport.update({
  id: '/settings/system',
  path: '/settings/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsConfigRoute = SettingsConfigRouteImport.update({
  id: '/settings/config',
  path: '/settings/config',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsIdRoute = DeploymentsIdRouteImport.update({
  id: '/deployments/$id',
  path: '/deployments/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/logs': typeof LogsRoute
  '/notifications': typeof NotificationsRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/specs': typeof SpecsRoute
  '/deployments/$id': typeof DeploymentsIdRoute
  '/settings/config': typeof SettingsConfigRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/users': typeof SettingsUsersRoute
  '/deployments': typeof DeploymentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/logs': typeof LogsRoute
  '/notifications': typeof NotificationsRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/specs': typeof SpecsRoute
  '/deployments/$id': typeof DeploymentsIdRoute
  '/settings/config': typeof SettingsConfigRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/users': typeof SettingsUsersRoute
  '/deployments': typeof DeploymentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/logs': typeof LogsRoute
  '/notifications': typeof NotificationsRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/specs': typeof SpecsRoute
  '/deployments/$id': typeof DeploymentsIdRoute
  '/settings/config': typeof SettingsConfigRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/users': typeof SettingsUsersRoute
  '/deployments/': typeof DeploymentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/dashboard'
    | '/logs'
    | '/notifications'
    | '/resources'
    | '/services'
    | '/specs'
    | '/deployments/$id'
    | '/settings/config'
    | '/settings/system'
    | '/settings/users'
    | '/deployments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/console'
    | '/dashboard'
    | '/logs'
    | '/notifications'
    | '/resources'
    | '/services'
    | '/specs'
    | '/deployments/$id'
    | '/settings/config'
    | '/settings/system'
    | '/settings/users'
    | '/deployments'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/dashboard'
    | '/logs'
    | '/notifications'
    | '/resources'
    | '/services'
    | '/specs'
    | '/deployments/$id'
    | '/settings/config'
    | '/settings/system'
    | '/settings/users'
    | '/deployments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRoute
  DashboardRoute: typeof DashboardRoute
  LogsRoute: typeof LogsRoute
  NotificationsRoute: typeof NotificationsRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRoute
  SpecsRoute: typeof SpecsRoute
  DeploymentsIdRoute: typeof DeploymentsIdRoute
  SettingsConfigRoute: typeof SettingsConfigRoute
  SettingsSystemRoute: typeof SettingsSystemRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  DeploymentsIndexRoute: typeof DeploymentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/specs': {
      id: '/specs'
      path: '/specs'
      fullPath: '/specs'
      preLoaderRoute: typeof SpecsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/': {
      id: '/deployments/'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DeploymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/system': {
      id: '/settings/system'
      path: '/settings/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof SettingsSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/config': {
      id: '/settings/config'
      path: '/settings/config'
      fullPath: '/settings/config'
      preLoaderRoute: typeof SettingsConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/$id': {
      id: '/deployments/$id'
      path: '/deployments/$id'
      fullPath: '/deployments/$id'
      preLoaderRoute: typeof DeploymentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRoute,
  DashboardRoute: DashboardRoute,
  LogsRoute: LogsRoute,
  NotificationsRoute: NotificationsRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRoute,
  SpecsRoute: SpecsRoute,
  DeploymentsIdRoute: DeploymentsIdRoute,
  SettingsConfigRoute: SettingsConfigRoute,
  SettingsSystemRoute: SettingsSystemRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  DeploymentsIndexRoute: DeploymentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
